"""Update device schema for vision

Revision ID: 5331f0f4ef01
Revises: 1ff64ec7dc9c
Create Date: 2026-06-30 12:18:26.929317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5331f0f4ef01'
down_revision = '1ff64ec7dc9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('factory_mac', sa.String(length=17), nullable=False))
    op.add_column('devices', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('public_key', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('firmware_version', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('devices', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_constraint('motion_events_device_id_fkey', 'motion_events', type_='foreignkey')
    op.drop_constraint('devices_device_id_key', 'devices', type_='unique')
    op.create_index(op.f('ix_devices_factory_mac'), 'devices', ['factory_mac'], unique=True)
    op.create_foreign_key(None, 'devices', 'users', ['owner_id'], ['id'])
    op.drop_column('devices', 'owner_email')
    op.drop_column('devices', 'device_id')
    op.alter_column('motion_events', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='device_id::integer')
    op.create_foreign_key(None, 'motion_events', 'devices', ['device_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))  # type: ignore
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_constraint(None, 'motion_events', type_='foreignkey')  # type: ignore
    op.create_foreign_key('motion_events_device_id_fkey', 'motion_events', 'devices', ['device_id'], ['device_id'])
    op.alter_column('motion_events', 'device_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('devices', sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('owner_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')  # type: ignore
    op.drop_index(op.f('ix_devices_factory_mac'), table_name='devices')
    op.create_unique_constraint('devices_device_id_key', 'devices', ['device_id'])
    op.drop_column('devices', 'last_seen')
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'firmware_version')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'public_key')
    op.drop_column('devices', 'owner_id')
    op.drop_column('devices', 'factory_mac')
    # ### end Alembic commands ###
