"""Change device ID to UUID

Revision ID: f695ef481452
Revises: 5331f0f4ef01
Create Date: 2026-06-30 15:52:28.427658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f695ef481452'
down_revision = '5331f0f4ef01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Clear existing data to avoid complex type casting matching
    op.execute("TRUNCATE TABLE motion_events, devices CASCADE")

    # Drop foreign key first
    op.drop_constraint('motion_events_device_id_fkey', 'motion_events', type_='foreignkey')

    # Drop server default on devices.id
    op.execute('ALTER TABLE devices ALTER COLUMN id DROP DEFAULT')

    op.alter_column('devices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using='gen_random_uuid()',
               existing_nullable=False)
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
               
    op.alter_column('motion_events', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using='gen_random_uuid()',
               existing_nullable=False)
    op.alter_column('motion_events', 'motion_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('motion_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # Recreate foreign key
    op.create_foreign_key('motion_events_device_id_fkey', 'motion_events', 'devices', ['device_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motion_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('motion_events', 'motion_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('motion_events', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('devices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('devices_id_seq'::regclass)"))
    # ### end Alembic commands ###
